mj:
  task-store:
    type: redis
    timeout: 10d
  api-secret: ${MJ-PROXY-API-SECRET}
  translate-way: gpt
  openai:
    gpt-api-key: ${OPENAI-API-OFFICIAL-KEY}
    timeout: 30
    model: gpt-3.5-turbo
    max-tokens: 2048
    temperature: 0
  accounts:
    - guild-id: ${DISCORD-SERVER-ID}
      channel-id: ${DISCORD-CHANNEL-ID}
      user-token: ${DISCORD-USER-TOKEN}
      user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
      core-size: 3
      queue-size: 10
      timeout-minutes: 5

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: ${AZURE_LAB_KV_ENDPOINT}
  redis:
    host: ${REDIS-HOST}
    port: ${REDIS-PORT}
    password: ${REDIS-PASSWORD}

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enable: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics